### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Biggitybaked** [LOoLzeC/ASU#18]
Already up to date.                                        Traceback (most recent call last):
  File "ASU.py", line 7, in <module>                           main.regis()                                             File "<string>", line 149, in __init__
  File "<string>", line 168, in checkSession                 File "<string>", line 177, in cek                          File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 75, in get                     return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ranch-19.joomla.com', port=443): Max retries exceeded with url: /trialconfirm.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7d381aba10>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))

Any ideas?

**Comment by LycanOskari** [comment]
the same happens to me
