### ISSUE TITLE
FIX PROBLEM

### ISSUE THREAD

**Issue by stepsgdo** [LOoLzeC/ASU#19]
BAGAIMANA SOLUSINYA INI LOR

[?> 3
[!] tekan enter untuk menghubungi deray (whatsapp)
Traceback (most recent call last):
  File "ASU.py", line 7, in <module>
    main.regis()
  File "<string>", line 149, in __init__
  File "<string>", line 172, in checkSession
  File "<string>", line 49, in __init__
  File "<string>", line 55, in menu
  File "<string>", line 64, in c
  File "<string>", line 76, in year
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by BerkahMedia** [comment]
No wa nya berapa kk
